baseURL = "https://ferrydao.com/"
languageCode = "en-us"
title = "摆渡咨询·FerryDAO"
themesDir = "../.."
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logo_w.png"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/logo_w.png"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "FerryDAO"

  [params.homepage_meta_tags]
    meta_description = "FerryDAO 是一个去中心化商业战略咨询社区。我们帮助科技从业者建立他们的事业，提自我价值，并过上他们向往的生活。"
    meta_og_title = "摆渡咨询·FerryDAO"
    meta_og_type = "website"
    meta_og_url = "https://ferrydao.com/"
    meta_og_image = ""
    meta_og_description = "FerryDAO 是一个去中心化商业战略咨询社区。我们帮助科技从业者建立他们的事业，提自我价值，并过上他们向往的生活。"
    meta_twitter_card = "summary"
    meta_twitter_site = "@ferrydao"
    meta_twitter_creator = "@ferrydao"

[[menu.main]]
	name = "咨询服务"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "咨询资源"
    url = "https://www.wolai.com/ferrydao/qHaomr54kbTCaZDZY1Mc5J" 
    weight = 2
    
# [[menu.main]]
#    name = "加入社区"
#    url = "/history/"
#    weight = 3

[[menu.main]]
    name = "了解我们"
    url = "https://www.wolai.com/ferrydao/gdXagEudfLLKCvUowgrtBz"
    weight = 4
    
[[menu.main]]
    name = "联系我们"
    url = "https://www.wolai.com/f/tXPeVF61aSad1DmN9Vr5nU"
    weight = 5

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
